import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Every docs instance shares this file. Each one builds its sidebar from the
// folder structure of its own docs directory: folder order comes from the
// _category_.json position fields, page order from sidebar_position.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
